[package]
name = "nutrifi-staking"
version = "0.1.0"
description = "NutriFi liquid-staking program: deposit SOL, mint nSOL, accrue NUT rewards."
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "nutrifi_staking"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = { version = "0.31.1", features = ["mint", "token"] }
